// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HbaseProtocol.proto

package com.liumm.hbase.endpiont;

@SuppressWarnings("AliMissingOverrideAnnotation")
public final class HbaseProtocol {
  private HbaseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C503HbaseRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string jsonStr = 1;
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    boolean hasJsonStr();
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    java.lang.String getJsonStr();
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonStrBytes();
  }
  /**
   * Protobuf type {@code C503HbaseRequest}
   */
  @SuppressWarnings("AliMissingOverrideAnnotation")
  public static final class C503HbaseRequest extends
      com.google.protobuf.GeneratedMessage
      implements C503HbaseRequestOrBuilder {
    // Use C503HbaseRequest.newBuilder() to construct.
    private C503HbaseRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C503HbaseRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C503HbaseRequest defaultInstance;
    public static C503HbaseRequest getDefaultInstance() {
      return defaultInstance;
    }

    public C503HbaseRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C503HbaseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jsonStr_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.class, com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<C503HbaseRequest> PARSER =
        new com.google.protobuf.AbstractParser<C503HbaseRequest>() {
      public C503HbaseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C503HbaseRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C503HbaseRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string jsonStr = 1;
    public static final int JSONSTR_FIELD_NUMBER = 1;
    private java.lang.Object jsonStr_;
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    public boolean hasJsonStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    public java.lang.String getJsonStr() {
      java.lang.Object ref = jsonStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string jsonStr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonStrBytes() {
      java.lang.Object ref = jsonStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      jsonStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) {
          return isInitialized == 1;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getJsonStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getJsonStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest)) {
        return super.equals(obj);
      }
      com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest other = (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest) obj;

      boolean result = true;
      result = result && (hasJsonStr() == other.hasJsonStr());
      if (hasJsonStr()) {
        result = result && getJsonStr()
            .equals(other.getJsonStr());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasJsonStr()) {
        hash = (37 * hash) + JSONSTR_FIELD_NUMBER;
        hash = (53 * hash) + getJsonStr().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C503HbaseRequest}
     */
    @SuppressWarnings("AliMissingOverrideAnnotation")
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.class, com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.Builder.class);
      }

      // Construct using com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jsonStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseRequest_descriptor;
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest getDefaultInstanceForType() {
        return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.getDefaultInstance();
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest build() {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest buildPartial() {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest result = new com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jsonStr_ = jsonStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest) {
          return mergeFrom((com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest other) {
        if (other == com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.getDefaultInstance()) return this;
        if (other.hasJsonStr()) {
          bitField0_ |= 0x00000001;
          jsonStr_ = other.jsonStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string jsonStr = 1;
      private java.lang.Object jsonStr_ = "";
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public boolean hasJsonStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public java.lang.String getJsonStr() {
        java.lang.Object ref = jsonStr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          jsonStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonStrBytes() {
        java.lang.Object ref = jsonStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public Builder setJsonStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public Builder clearJsonStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonStr_ = getDefaultInstance().getJsonStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string jsonStr = 1;</code>
       */
      public Builder setJsonStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonStr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:C503HbaseRequest)
    }

    static {
      defaultInstance = new C503HbaseRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C503HbaseRequest)
  }

  public interface C503HbaseResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string result = 1;
    /**
     * <code>optional string result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code C503HbaseResponse}
   */
  @SuppressWarnings("AliMissingOverrideAnnotation")
  public static final class C503HbaseResponse extends
      com.google.protobuf.GeneratedMessage
      implements C503HbaseResponseOrBuilder {
    // Use C503HbaseResponse.newBuilder() to construct.
    private C503HbaseResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C503HbaseResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C503HbaseResponse defaultInstance;
    public static C503HbaseResponse getDefaultInstance() {
      return defaultInstance;
    }

    public C503HbaseResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C503HbaseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              result_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.class, com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<C503HbaseResponse> PARSER =
        new com.google.protobuf.AbstractParser<C503HbaseResponse>() {
      public C503HbaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C503HbaseResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C503HbaseResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.lang.Object result_;
    /**
     * <code>optional string result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse)) {
        return super.equals(obj);
      }
      com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse other = (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C503HbaseResponse}
     */
    @SuppressWarnings("AliMissingOverrideAnnotation")
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.class, com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.Builder.class);
      }

      // Construct using com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liumm.hbase.endpiont.HbaseProtocol.internal_static_C503HbaseResponse_descriptor;
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse getDefaultInstanceForType() {
        return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance();
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse build() {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse buildPartial() {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse result = new com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse) {
          return mergeFrom((com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse other) {
        if (other == com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          bitField0_ |= 0x00000001;
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string result = 1;
      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:C503HbaseResponse)
    }

    static {
      defaultInstance = new C503HbaseResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C503HbaseResponse)
  }

  /**
   * Protobuf service {@code C503HbaseQueryService}
   */
  @SuppressWarnings("AliMissingOverrideAnnotation")
  public static abstract class C503HbaseQueryService
      implements com.google.protobuf.Service {
    protected C503HbaseQueryService() {}

    public interface Interface {
      /**
       * <code>rpc query(.C503HbaseRequest) returns (.C503HbaseResponse);</code>
       */
      public abstract void query(
          com.google.protobuf.RpcController controller,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request,
          com.google.protobuf.RpcCallback<com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new C503HbaseQueryService() {
        @java.lang.Override
        public  void query(
            com.google.protobuf.RpcController controller,
            com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request,
            com.google.protobuf.RpcCallback<com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse> done) {
          impl.query(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.query(controller, (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc query(.C503HbaseRequest) returns (.C503HbaseResponse);</code>
     */
    public abstract void query(
        com.google.protobuf.RpcController controller,
        com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request,
        com.google.protobuf.RpcCallback<com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.liumm.hbase.endpiont.HbaseProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.query(controller, (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest)request,
            com.google.protobuf.RpcUtil.<com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    @SuppressWarnings("AliMissingOverrideAnnotation")
    public static final class Stub extends com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseQueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void query(
          com.google.protobuf.RpcController controller,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request,
          com.google.protobuf.RpcCallback<com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.class,
            com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse query(
          com.google.protobuf.RpcController controller,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request)
          throws com.google.protobuf.ServiceException;
    }

    @SuppressWarnings("AliMissingOverrideAnnotation")
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse query(
          com.google.protobuf.RpcController controller,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.liumm.hbase.endpiont.HbaseProtocol.C503HbaseResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:C503HbaseQueryService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C503HbaseRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C503HbaseRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C503HbaseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C503HbaseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HbaseProtocol.proto\"#\n\020C503HbaseReques" +
      "t\022\017\n\007jsonStr\030\001 \001(\t\"#\n\021C503HbaseResponse\022" +
      "\016\n\006result\030\001 \001(\t2G\n\025C503HbaseQueryService" +
      "\022.\n\005query\022\021.C503HbaseRequest\032\022.C503Hbase" +
      "ResponseB1\n\030com.liumm.hbase.endpiontB\rHb" +
      "aseProtocolH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_C503HbaseRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_C503HbaseRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C503HbaseRequest_descriptor,
              new java.lang.String[] { "JsonStr", });
          internal_static_C503HbaseResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_C503HbaseResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C503HbaseResponse_descriptor,
              new java.lang.String[] { "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
